name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  deployments: write

# Environment variables
env:
  HUGO_VERSION: 0.121.0

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Verify Hugo Installation
        run: hugo version

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: List repository contents
        run: |
          echo "Current directory:"
          pwd
          echo "\nRepository contents:"
          ls -la
          echo "\nTheme directory contents:"
          ls -la themes/ || echo "No themes directory found"
          echo "\nConfig file:"
          cat hugo.yaml || echo "hugo.yaml not found"

      - name: Build with verbose output
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/" --verbose

      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la ./public || echo "Public directory not found"
          echo "\nTotal files in public:"
          find ./public -type f | wc -l || echo "Cannot count files"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 